#! /usr/bin/env bash

if [ "${1}" != "version" ]; then
  >&2 echo "unknown command ${1}"
  exit 1;
fi

if [ "${GO_TEST_VERSION}" = "" ]; then
  >&2 echo "GO_TEST_VERSION environment variable must be set"
  exit 1;
fi

echo "go version go${GO_TEST_VERSION} darwin/amd64"
exit 0
