#! /usr/bin/env bash

if [ "${1}" != "--version" ]; then
  >&2 echo "unknown command ${1}"
  exit 1;
fi

if [ "${RUST_TEST_VERSION}" = "" ]; then
  >&2 echo "RUST_TEST_VERSION environment variable must be set"
  exit 1;
fi

echo "rustc ${RUST_TEST_VERSION} (9d1b2106e 2022-02-23)"
exit 0
